### ISSUE TITLE
mariadb 10.1.43 docker image fails to start (10.1.41 works fine)

### ISSUE THREAD

**Issue by jgb** [docker-library/mariadb#274] opened 2019-11-18 10:53 UTC
Hello,

I was using the mariadb 10.1.41 docker image, worked fine, but when I adjusted my docker-compose.yml to use 10.1.43 my databases fail to start.
These are the last log entries:

```
2019-11-18 11:25:21+01:00 [Note] [Entrypoint]: Temporary server started.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
ERROR 1105 (HY000) at line 146984: ORDER BY ignored as there is a user-defined clustered index in the table 'time_zone_transition'
```

And then the docker container exists.

What can be done to fix this?

Greetings,

jgb

**Comment by wglambert** [comment] 2019-11-18 21:43
Duplicate of https://github.com/docker-library/mariadb/issues/262

This is an upstream issue, a workaround is to pass `MYSQL_INITDB_SKIP_TZINFO=1`
https://github.com/docker-library/mariadb/issues/262#issuecomment-536405303

**Closed by wglambert** 2019-11-18 21:43 UTC
