### ISSUE TITLE
Add a HEALTHCHECK stanza

### ISSUE THREAD

**Issue by evanp** [docker-library/mariadb#128] opened 2017-09-20 21:52 UTC
There should be a healthcheck that makes sure the server is up and servicing connections.

**Comment by yosifkit** [comment] 2017-09-20 23:31
Duplicate of https://github.com/docker-library/mariadb/issues/94. Related https://github.com/docker-library/cassandra/pull/76.

>  I have not seen a need for general health checks in the official-images; either the container is up or it is not and anything more granular is up to the user to define for their environment.
>
> \- https://github.com/docker-library/rabbitmq/pull/174#issuecomment-330687112

**Closed by yosifkit** 2017-09-20 23:31 UTC
