### ISSUE TITLE
Environment variable MYSQL_ROOT_PASSWORD not working

### ISSUE THREAD

**Issue by Lentolo** [docker-library/mariadb#268] opened 2019-10-25 10:47 UTC
Hi, 
I am trying to create a docker container with the below script:

docker run \
--name mydb \
--publish 3306:3306 \
--env 'MYSQL_ROOT_PASSWORD=mySecret1!' \
--env 'MYSQL_DATABASE=mydb' \
--env 'MYSQL_USER=mydb' \
--env 'MYSQL_PASSWORD=mydb1!' \
--detach \
mariadb:latest

Th container is created but the environment variables are not used.
No volumes are defined, and the image is the latest one.
What am i doing wrong?
Thanks

**Comment by wglambert** [comment] 2019-10-25 16:26
Duplicate of https://github.com/docker-library/mariadb/issues/183
>We don't escape any password characters since we didn't want to implement the equivalent of `mysql_real_escape_string` in bash and didn't want to burden the image with an install of a library/language just for this purpose.

The environment variables are added appropriately, but they contain invalid characters as input to mariadb
```console
$ docker run --name mydb --publish 3306:3306 --env 'MYSQL_ROOT_PASSWORD=mySecret1!' --detach mariadb:latest
9879713f02479c9c1cf2553a4d1d8af0d95a4891e05f58ee415de6eb2e5d72e2

$ docker inspect 9879 | grep -i env -A1
            "Env": [
                "MYSQL_ROOT_PASSWORD=mySecret1!",
```

**Closed by wglambert** 2019-10-25 16:26 UTC
Labels: question
