### ISSUE TITLE
Set default `wait_timeout` value to 28800

### ISSUE THREAD

**Issue by eipiminus1** [docker-library/mariadb#113] opened 2017-07-09 20:24 UTC
The mariadb documentation says the default value for `wait_timeout` is 28800.

The container seems to have a value of 600 as default for the global variable.

**Steps to reproduce**
`docker run -d --name mydb -it -e MYSQL_ROOT_PASSWORD=123456 mariadb`
`docker exec -it mydb bash`
`mysql -p123456`
`SHOW global VARIABLES LIKE "wait_timeout";`

**returns**
```
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 600   |
+---------------+-------+
```

**expected**
```
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
```

This leads to problems with some other default configurations that assumes 8 hours timeout: In my case it was with flask-sqlalchemy that resets a timeout after 2 hours: https://github.com/mitsuhiko/flask-sqlalchemy/issues/91

**Comment by tianon** [comment] 2017-07-10 22:35
I can confirm that it is happening, although I can't say why just yet:
```console

$ docker pull mariadb:10
10: Pulling from library/mariadb
Digest: sha256:0b892e7e272381f95d74b1c01faf2ff57bdbb69489ff0dcf0f0e1f79006a916c
Status: Image is up to date for mariadb:10

$ docker run -dit --name mydb -e MYSQL_ROOT_PASSWORD=123456 mariadb:10
2081f0942aeb930ebed16bded4897b16956b7c5ce0e36234338cad35d036b553

$ docker exec -it mydb mysql -uroot -p123456
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.2.6-MariaDB-10.2.6+maria~jessie mariadb.org binary distribution

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW global VARIABLES LIKE 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 600   |
+---------------+-------+
1 row in set (0.00 sec)

MariaDB [(none)]> 
```

**Comment by tianon** [comment] 2017-07-10 22:37
Found it -- it's MariaDB's Debian package which sets this value: https://github.com/MariaDB/server/blob/5ff2db7f67401511b30dbd3fc69a1ea87d7e8cc4/debian/additions/my.cnf#L53

**Comment by tianon** [comment] 2017-07-10 22:39
Closing since this is working-as-designed, but here's a simple workaround:

```console

$ docker run -dit --name mydb -e MYSQL_ROOT_PASSWORD=123456 mariadb:10 --wait_timeout=28800
2e414afe04f4ed0bad8d13f41de2db77a0fe7abdc7570b714926354e95b64329

$ docker exec -it mydb mysql -uroot -p123456
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.2.6-MariaDB-10.2.6+maria~jessie mariadb.org binary distribution

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW global VARIABLES LIKE 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.00 sec)

MariaDB [(none)]> 
```

**Closed by tianon** 2017-07-10 22:39 UTC

**Comment by ickata** [comment] 2018-04-12 15:19
How the above workaround should look in `docker-compose`? I tried:

```
      command: mysqld --wait_timeout=28800
```

```
      args:
         - wait_timeout=28800
```

but w/o success.

**Comment by tianon** [comment] 2018-04-12 16:37
I'd recommend something like the following:

```yaml
        command: [
            '--wait_timeout=28800',
        ]

**Comment by tanji** [comment] 2018-04-12 20:26
Hey guys!
`wait_timeout` takes a different value depending if it's interactive or not.
If it's non-interactive, the value will be derived from the `wait_timeout` configuration parameter. Otherwise, it will be derived from the `interactive_timeout` configuration parameter, which is what you will see if you open a session with the `mysql` client.

Reference: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

**Comment by ickata** [comment] 2018-04-13 14:59
Hi all,

@tianon – many thanks, that helped!

@tanji – `wait_timeout` is what I really needed. The default value for the MariaDB container was 600 seconds, resulting in connection being closed every 10 minutes and sometimes a NodeJS worker not being restarted.

**Comment by w7089** [comment] 2019-08-07 15:39
Seems like workaround is [not effective](https://github.com/moby/moby/issues/37822) if MariaDB is deployed as Docker Swarm service.
More [info](https://flavio.aiello.ch/mariadb-automatic-docker-limits/)

> Closing since this is working-as-designed, but here's a simple workaround:
> 
> ```
> $ docker run -dit --name mydb -e MYSQL_ROOT_PASSWORD=123456 mariadb:10 --wait_timeout=28800
> 2e414afe04f4ed0bad8d13f41de2db77a0fe7abdc7570b714926354e95b64329
> 
> $ docker exec -it mydb mysql -uroot -p123456
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 8
> Server version: 10.2.6-MariaDB-10.2.6+maria~jessie mariadb.org binary distribution
> 
> Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MariaDB [(none)]> SHOW global VARIABLES LIKE 'wait_timeout';
> +---------------+-------+
> | Variable_name | Value |
> +---------------+-------+
> | wait_timeout  | 28800 |
> +---------------+-------+
> 1 row in set (0.00 sec)
> 
> MariaDB [(none)]> 
> ```

**Comment by yosifkit** [comment] 2019-08-08 21:15
Thanks for the info that Docker overlay networks also be the cause of connection timeouts.

I'd strongly caution against using `/sys/fs/cgroup/memory/memory.limit_in_bytes` without first checking that it is a useful value. If the container doesn't have a limit set, it will probably be much [larger than expected](https://unix.stackexchange.com/questions/420906/what-is-the-value-for-the-cgroups-limit-in-bytes-if-the-memory-is-not-restricte).

```console
$ docker run --rm bash cat /sys/fs/cgroup/memory/memory.limit_in_bytes 
9223372036854771712
$ docker run --rm bash cat /sys/fs/cgroup/memory/memory.limit_in_bytes | awk '{ print int($1/1024/1024/1024) }'
8589934591
$ # that's in GiB
$ docker run --rm bash cat /sys/fs/cgroup/memory/memory.limit_in_bytes | awk '{ print int($1/1024/1024/1024/1024/1024/1024) }'
7
$ # or ~7 Exabytes
```

**Comment by darioseidl** [comment] 2021-11-03 13:34
Just for info, it appears to me that the default `wait_timeout` has changed from 600 s for mariadb:10.3 to the upstream default of 28800 s in mariadb:10.5.

```
$ docker run -dit --name mydb10.5 -e MYSQL_ROOT_PASSWORD=123456 mariadb:10.5
b4b1b0097459c06e087119f30595574c7b669521500f7e5cac0ed653816dec6c

$ docker exec -it mydb10.5 mysql -uroot -p123456 --protocol=tcp
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 3
Server version: 10.5.12-MariaDB-1:10.5.12+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW global VARIABLES LIKE 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.002 sec)
```

**Comment by grooverdan** [comment] 2021-11-03 21:33
Right, the Ubuntu-20.04 / MariaDB-10.5  is much closer to the upstream:
```
$ podman run mariadb:10.5 my_print_defaults --mysqld
--socket=/run/mysqld/mysqld.sock
--skip-host-cache
--skip-name-resolve
--pid-file=/run/mysqld/mysqld.pid
--basedir=/usr
--datadir=/var/lib/mysql
--tmpdir=/tmp
--lc-messages-dir=/usr/share/mysql
--lc-messages=en_US
--skip-external-locking
--expire_logs_days=10
--character-set-server=utf8mb4
--collation-server=utf8mb4_general_ci
```
Some of which are default already (I'm not sure why).

 I hope this is generally more convenient.

**Comment by klypnick** [comment] 2022-09-11 23:32
In docker swarm configurations there is an internal TCP idle timeout at 15 minutes which causes issues if both the client and server expect the session to be able to remain idle for 8 hours.

**Comment by grooverdan** [comment] 2022-09-12 00:22
@klypnick ok, so I probably could include this in some FAQ documentation. Can you include an example of the client error so I can write it quicker.

**Comment by klypnick** [comment] 2022-09-13 21:32
https://github.com/moby/moby/issues/37822

sadly i have no actual error message, it took a while to diagnose why occasional DB requests were failing silently.  The client was attempting to maintain an active connection pool but after 15 minutes of idleness IPVS inside docker swarm would tear down the TCP mapping and the request would simply fail, this would repeat until all pool members were discovered to be non functional and finally a new DB session would start and transactions would work again.

It was discovered through software making use of the knex.js npm package.  Setting the minimum pool size to 0 causing them to always reap after 30 second solved our issue, as did setting wait_timeout and interactive_timeout below 15 minutes initially. 

I thought it was worth mentioning here as I was unaware of the 15 minute TCP timeout in docker swarm IPVS
