### ISSUE TITLE
Error running local build - running docker-entrypoint.sh

### ISSUE THREAD

**Issue by richard-moss** [docker-library/mariadb#148] opened 2018-01-11 01:21 UTC
Hi there,

I got an error running this from a local build (macOS) with the container failing to exec docker-entrypoint.sh on container start.

After the COPY in I added:

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

...fixed the problem

**Comment by tianon** [comment] 2018-01-11 01:33
Duplicate of https://github.com/docker-library/mariadb/pull/87.

If you apply the `chmod` on your local copy before you build, it will have the same effect.

**Closed by tianon** 2018-01-11 01:33 UTC

**Comment by richard-moss** [comment] 2018-01-11 02:06
gotcha! 
...thanks - didn't DL it via git, so it didn't have the default +x
